import { createPageMetadata } from "@/lib/i18n/page-metadata"
import { LocalizedLegal } from "@/components/localized-legal"
import { Link } from "@/i18n/navigation"
import { ScrollSpySidebar } from "@/components/scroll-spy-sidebar"
import { diatypeItalicFont } from "@/app/site-fonts"
import { resolveLocaleParam, type LocaleParamsProps } from "@/lib/i18n/locale-params"

const sections = [
  { id: "eligibility", title: "1. Eligibility" },
  { id: "avana-protocol", title: "2. Avana Protocol" },
  { id: "the-services", title: "3. The Services" },
  { id: "informational-resources", title: "4. Informational Resources" },
  { id: "prohibited-activities", title: "5. Prohibited Activities" },
  { id: "intellectual-property", title: "6. Intellectual Property" },
  { id: "term-termination", title: "7. Term; Termination" },
  { id: "risks", title: "8. Risks" },
  { id: "disclaimer-of-warranties", title: "9. Disclaimer of Warranties" },
  { id: "dispute-resolution", title: "10. Dispute Resolution" },
  { id: "third-party-services", title: "11. Third-Party Services" },
  { id: "general-provisions", title: "12. General Provisions" },
]

export async function generateMetadata({ params }: LocaleParamsProps) {
  const locale = await resolveLocaleParam(params)
  return createPageMetadata(locale, "terms", "/terms")
}

export default async function TermsPage({ params }: LocaleParamsProps) {
  const locale = await resolveLocaleParam(params)
  return (
    <LocalizedLegal locale={locale} kind="terms">
    <section className="py-12 md:py-24">
      <article className="site-content-shell">
        {/* Header */}
        <div className="flex flex-col items-start gap-6 mb-12">
          <h1 className={`${diatypeItalicFont.className} type-page-title italic text-gray-900`}>Terms of Service</h1>
          <hr className="w-full border-gray-200" />
        </div>

        {/* Two-column layout */}
        <div className="flex min-w-0 flex-col gap-12 xl:flex-row xl:items-start xl:gap-24">
          {/* Main content */}
          <div className="site-editorial-content min-w-0 flex-1 max-w-3xl [&_strong]:font-semibold [&_strong]:text-gray-900 [&_h4]:mt-10 [&_h4]:mb-4 [&_p]:mb-4 [&_ul]:list-disc [&_ul]:pl-6 [&_ul]:mb-4 [&_li]:mb-2 [&_a]:text-blue-600 [&_a]:hover:underline">
            <p><em className="text-gray-500">Last Modified: January 18, 2026</em></p>

            <p>
              These Terms of Service (the &quot;<strong>Terms</strong>&quot;) constitute a legally binding agreement made between you (&quot;<strong>you</strong>&quot;) and Avana (&quot;<strong>Avana,</strong>&quot; &quot;<strong>we,</strong>&quot; &quot;<strong>our</strong>&quot; or &quot;<strong>us</strong>&quot;) concerning your access to and use of the Testnet (as defined below), Avana Protocol (as defined below), the Informational Resources (as defined below) and such other products and services related to Avana (as defined below) that may be offered by Avana from time to time (collectively, the &quot;<strong>Services</strong>&quot;). By accessing or using the Services, you agree that you have read, understand and accept all of the terms and conditions contained in the Terms. If you do not agree to all of the terms and conditions of the Terms, you may not access or use the Services.
            </p>

            <p>
              <strong>Amendment of the Terms</strong>. We may amend or modify the Terms at any time by posting the revised version on{" "}
              <Link href="/terms">/terms</Link> and/or providing a copy to you (&quot;<strong>Revised Terms</strong>&quot;). Such Revised Terms shall be effective as of the time the Revised Terms are posted on the{" "}
              <Link href="/terms">/terms</Link>. Your continued use of the Services after the posting of Revised Terms constitutes your acceptance of such Revised Terms. If you do not agree with any such revisions, your sole and exclusive remedy is to terminate your use of the Services.
            </p>

            <p>
              <strong>Technical Services Only</strong>. THE SERVICES INCLUDE, AMONG OTHER THINGS, THE INFORMATIONAL RESOURCES, WHICH MAY PROVIDE INFORMATION RELATED TO AVANA, A DECENTRALIZED FINANCE PROTOCOL FOR LENDING AND BORROWING AGAINST LP POSITIONS (&quot;<strong>AVANA PROTOCOL</strong>&quot;). AVANA IS NOT A BROKER, DEALER, EXCHANGE, INVESTMENT ADVISER, CUSTODIAN OR FINANCIAL SERVICE PROVIDER OF ANY KIND. WE DO NOT HAVE A FIDUCIARY RELATIONSHIP WITH, OR OBLIGATION TO, YOU IN CONNECTION WITH THE SERVICES.
            </p>

            <p>
              <strong>Binding Arbitration; Class Action and Jury Trial Waiver</strong>. PLEASE BE AWARE THAT SECTION 10 (DISPUTE RESOLUTION; AGREEMENT TO ARBITRATE) GOVERNS THE RESOLUTION OF DISPUTES BETWEEN YOU AND AVANA. SECTION 10 INCLUDES AN AGREEMENT TO ARBITRATE, WHICH REQUIRES, WITH LIMITED EXCEPTIONS, THAT ALL DISPUTES BETWEEN YOU AND US SHALL BE RESOLVED BY BINDING AND FINAL ARBITRATION. SECTION 10 ALSO CONTAINS A CLASS ACTION AND JURY TRIAL WAIVER. PLEASE READ SECTION 10 CAREFULLY.
            </p>

            <p>
              <strong>Privacy Policy</strong>. Your personal information and privacy are important to us. The collection, use and sharing of your personal information through the Services and while you use the Services are subject to our{" "}
              <Link href="/privacy">Privacy Policy</Link>, which is hereby incorporated into the Terms.
            </p>

            <h4 id="eligibility">1. Eligibility</h4>
            <p>To be eligible to access or use the Services, you must satisfy each of the following eligibility requirements:</p>
            <p>1.1. You are at least eighteen (18) years of age, or are the legal age for entering into legally binding agreements under applicable law; and</p>
            <p>1.2. You are not, nor are you an entity that is, or an entity owned or controlled by any person or entity that is, or conducting any activities yourself or on behalf of any person or entity that is, the subject of any sanctions administered or enforced by the U.S. Department of the Treasury&apos;s Office of Foreign Assets Control, the U.S. Department of State or any other governmental authority with jurisdiction over the party; identified on the Denied Persons, Entity or Unverified Lists of the U.S. Department of Commerce&apos;s Bureau of Industry and Security; or located, organized or resident in a country or territory that is, or whose government is, the subject of economic sanctions (each, a &quot;<strong>Restricted Person</strong>&quot;).</p>

            <h4 id="avana-protocol">2. Avana Protocol</h4>
            <p>
              Avana is a decentralized finance protocol built on open source software that enables users to use their LP (Liquidity Provider) positions as collateral for borrowing (&quot;<strong>Avana Protocol</strong>&quot;). The Avana Protocol includes functionality whereby certain open source smart contracts can receive and hold certain digital currency or other crypto assets from certain supported blockchain networks such as Ethereum. There is a risk that the open source software, including any upgrades, that the Avana Protocol is built on may introduce bugs, viruses, Trojan horses, or other vulnerabilities or changes that could result in a partial or complete disruption of the protocol or loss, damage, or destruction of your crypto assets. The blockchain networks and crypto assets which can function with the Avana Protocol may also be subject to change at any time. We do not control what third-parties may build on the Avana Protocol, the activity of such parties, any user transacting on the protocol, or any data stored on the protocol itself, and we do not take possession, custody, or control over any virtual currency or other crypto assets on the Avana Protocol. Therefore, you acknowledge and agree that the Avana Protocol smart contracts are not part of our Services, and we have no obligations or liability to you in relation to your use of the Avana Protocol, and your use of the Avana Protocol is at your own risk.
            </p>

            <h4 id="the-services">3. The Services</h4>
            <p>
              3.1. <em>Testnet</em>. Avana deployed a testing environment for the Avana Protocol (the &quot;<strong>Testnet</strong>&quot;) that is designed to enable beta testers and developers to test and improve the security, experience and design of applications integrated with the Avana Protocol. Testnet tokens are for testing purposes only, are not transferable outside of the Testnet, have no monetary, tangible or meaningful value outside of the Testnet and cannot be used outside of the Testnet. Testnet tokens do not constitute currency or property of any type and are not redeemable, transferable, refundable or convertible for any fiat, crypto assets on the Avana Protocol or anything else of value. Avana may change, discontinue, or terminate, temporarily or permanently, all or any part of the Testnet, at any time and without notice.
            </p>
            <p>
              3.2. <em>Protocol Interface</em>. Avana operates a web interface that allows users to interact with the Avana Protocol smart contracts (the &quot;<strong>Protocol Interface</strong>&quot;). The Protocol Interface does not store, take custody of, control, send, or receive your crypto assets, except for receiving applicable gas fees. The Protocol Interface also does not have the ability to modify, reverse or otherwise alter any submitted transactions to the Ethereum blockchain, and will not have access to your private keys or the ability to control value on your behalf. We reserve the right to charge and modify the fees in connection with your use of the Protocol Interface.
            </p>

            <h4 id="informational-resources">4. Informational Resources</h4>
            <p>
              We may make certain informational resources relating to the Services available to you through the Website, including, without limitation, technical documentation, blog posts, data, articles, tutorials, social media posts and other informational content published by us, our employees or our marketing partners (&quot;<strong>Informational Resources</strong>&quot;). You acknowledge and agree that all such Informational Resources are intended for informational and educational purposes only and may not be the exclusive or sole source of information regarding the Services. Avana shall not be responsible or liable for any damage or loss caused or alleged to be caused by or in connection with the use or reliance on any Informational Resources.
            </p>

            <h4 id="prohibited-activities">5. Prohibited Activities</h4>
            <p>5.1. You shall not engage in any activities that negatively affect the technical performance of the Services, bypass or circumvent security features of the Services or otherwise disrupt or interfere with the functioning of the Services.</p>
            <p>5.2. You shall not violate or attempt to violate the security of the Services or otherwise misuse the foregoing, including, without limitation, by: (i) using any part of the Services or accessing data not intended for you or logging onto a server or an account that you are not authorized to access; (ii) disabling, removing, defeating or avoiding any security device or system; (iii) attempting to probe, scan or test the vulnerability of the Services or to breach security or authentication measures without proper authorization; (iv) attempting to interfere with the Services functionality, including but not limited to via means of submitting any malware or computer programming routines that may damage, disrupt or interfere with, intercept or expropriate any system or data, overloading, &quot;flooding,&quot; &quot;spamming,&quot; &quot;mailbombing&quot; or &quot;crashing&quot; the Services; (v) forging any transmission control protocol/internet protocol packet header or any part of the header information in any email or posting; or (vi) using the Services in a manner that exceeds reasonable request volume or constitutes excessive or abusive usage.</p>
            <p>5.3. You shall not, directly or indirectly: (i) disassemble, decompile, reverse engineer or use any other means to attempt to discover any source code of the Services, or the underlying ideas, file formats, algorithms or trade secrets therein (unless such source code is open sourced), unless such source code is subject to an open-source license; (ii) encumber, sublicense, transfer, rent, lease, time-share or use the Services in any service bureau arrangement or otherwise for the benefit of any third party; (iii) copy, distribute, manufacture, adapt, create derivative works of, translate, localize, port or otherwise modify any software code or documentation for the Services; (iv) knowingly introduce into the Services any malicious code, computer virus, spyware, scareware, Trojan horses, worms, malware or any other similar harmful, malicious or hidden programs or data; (v) use the Services to infringe upon, violate or misappropriate any third party&apos;s intellectual property rights, violating any law or regulation or being defamatory, trade libelous, threatening or harassing; or (vi) authorize or permit any third party to engage in any of the foregoing proscribed acts. For the avoidance of doubt, the restrictions set forth in this Section are in addition to, and in no way limit, any other restrictions or obligations applicable to you set forth in the Terms.</p>
            <p>5.4. You shall not use the Services to engage in illegal activity of any kind, including, without limitation, any activity that would violate, or assist in violation of, any law, statute, ordinance, regulation or sanctions programs administered under any applicable law.</p>

            <h4 id="intellectual-property">6. Intellectual Property</h4>
            <p>
              6.1. <em>License</em>. The Services and all of its contents as a whole and in part are protected by copyrights, trademarks, service marks, trade names, international treaties and/or other proprietary rights and applicable laws. You agree to protect the proprietary rights of us and all others having rights in the Services. Subject to these Terms, we grant you a limited, revocable, non-exclusive, non-sublicensable, non-transferable license to use the Services. You acquire absolutely no rights or licenses in or to the Services or materials contained within the Services and the limited right for you to access and use the Services in accordance with the Terms. Except for the limited license granted in these Terms, Avana and its licensors retain all right, title, interest and all proprietary rights in and to the Services, including, without limitation, copyrights, patents, trademarks, service marks and trade names. Avana may change, suspend or discontinue any aspect of the Services at any time, without any liability or obligation to you. Avana, its licensors and service providers reserve all other rights afforded to them but not granted in these Terms.
            </p>
            <p>
              6.2. <em>Third-Party Licenses</em>. Notwithstanding anything to the contrary in the Terms, the Services may contain software components released under separate open-source or business-source license terms, in which case those license terms will govern such software components.
            </p>
            <p>
              6.3. <em>Feedback</em>. With respect to any feedback you provide to Avana (whether orally or in writing) concerning the Services, including any features or functionalities thereof, and including identifying potential errors and improvements (&quot;<strong>Feedback</strong>&quot;), including, for the avoidance of doubt, any potential errors and improvements with respect to technical documentation, you hereby grant to Avana an exclusive, worldwide, perpetual, fully paid-up, royalty free, fully-sublicensable (through multiple tiers of sublicensees) and freely assignable and transferable license to use any Feedback for any purpose without payment or restriction. It is further understood that Avana&apos;s use of Feedback, if any, may be used by Avana or any of its designees in their sole discretion, and that Avana shall in no way be obliged to make any payment to you for or make use of any kind of the Feedback or part thereof.
            </p>
            <p>
              6.4. <em>Use of Trademarks and Other Marks or Rights</em>. You may not use any of our trademarks, trade names, service marks, copyrights or logos, or our licensors&apos;, or their licensors&apos; trademarks, trade names, service marks, copyrights or logos, including but not limited to the &quot;Avana&quot; name (collectively, the &quot;<strong>Marks</strong>&quot;): (i) for any purpose other than in connection with your use of the Services in accordance with these Terms; (ii) in any form, color or rendering other than as provided through the Services or create or use any translations, transliterations, stylizations, fonts, logos, variations or derivatives of or other alterations of or new trademarks containing or comprising the Marks or use any Mark together with any other trademark; and (iii) in any manner that creates or could reasonably create the impression that such Marks: (x) belong to or are associated with you or indicate the sponsorship or approval of us, our licensors, any partners or their licensors; (y) except as otherwise provided herein, are used with our, our licensors&apos;, partners&apos;, or their licensors&apos; consent; or (z) in any manner that harms or jeopardizes, or could reasonably be expected to materially harm or jeopardize, the value, validity, reputation or goodwill of the Marks. You acknowledge and agree that you have no ownership rights in or to any Marks, will not register or attempt to register any Mark or challenge our rights in the same, and that any goodwill arising from your use of the Marks as permitted hereunder will inure to the benefit of us, our licensors, partners or their licensors, as applicable. We may require you to cease using any Mark at any time, in our sole discretion.
            </p>

            <h4 id="term-termination">7. Term; Termination</h4>
            <p>7.1. The Terms are effective beginning when you first access or use the Services and ending when terminated as set forth in Section 7.2.</p>
            <p>7.2. Your right to use and access the Services will automatically terminate in the event you fail to comply with any of the terms and conditions of the Terms. Termination will be effective without notice.</p>
            <p>7.3. Upon termination of the Terms, your license rights will immediately terminate and you must immediately cease all use of the Services. Sections 5-12 of the Terms shall survive any such termination.</p>

            <h4 id="risks">8. Risks</h4>
            <p>8.1. You acknowledge and understand that the Services, the Avana Protocol and/or any underlying blockchain networks may not be available or appropriate for use in all jurisdictions and you may be subject to legal and regulatory compliance obligations in connection with your use of the Services in certain jurisdictions. By accessing or using the Services, you agree that you are solely and entirely responsible for compliance with all laws and regulations that may apply to you. You further agree that we have no obligation to inform you of any potential liabilities or violations of law or regulation that may arise in connection with your access and use of the Services, the Avana Protocol or Third-Party Services made available via the Avana Protocol, and that we are not liable in any respect for any failure by you to comply with any applicable laws or regulations.</p>
            <p>8.2. You acknowledge that the Services may incorporate experimental and novel technology and that the use of such technology involves a high degree of risk. For example, there are numerous reasons the Services or underlying blockchain networks or blockchain-based or software tools related to the Services could fail in an unexpected way, resulting in the total and absolute loss of any crypto assets held in your digital wallet. You hereby agree that you assume all risks in connection with your use of the Services and expressly waive and release Avana from any and all liability, claims, causes of action or damages arising out of or in any way relating to you obtaining or using Services.</p>
            <p>8.3. You understand and accept the risk of operational challenges related to the Services. For example, the Services and/or underlying blockchain networks may experience or be the subject of cyber-attacks, unexpected surges in transaction volume, botting or activity, or other operational or technical difficulties or vulnerabilities that may cause interruptions related to your use of the Services. You agree to accept the risk of a failure of the Services resulting from unanticipated or heightened technical difficulties or vulnerabilities, including those resulting from cyber-attacks. You agree to not hold Avana liable for any related losses and that you are accessing and using the Services and the Avana Protocol at your own risk.</p>
            <p>8.4. You agree that Avana is not responsible for any tax obligations that you may incur in connection with your use of the Services.</p>
            <p>8.5. You understand that the Ethereum blockchain and related DeFi protocols remain under development. As a result, you may be subject to certain technological and security risks when using the Services, in addition to uncertainty relating to crypto assets and blockchain transactions more generally.</p>
            <p>8.6. THE SERVICES MAY RELY ON EMERGING TECHNOLOGIES, INCLUDING, BUT NOT LIMITED TO, CRYPTOGRAPHY, SMART CONTRACTS AND OTHER BLOCKCHAIN-BASED TECHNOLOGIES. SOME FUNCTIONALITY IS SUBJECT TO INCREASED RISK THROUGH YOUR POTENTIAL MISUSE, SUCH AS MISUSES RELATED TO PUBLIC/PRIVATE KEY CRYPTOGRAPHY. BY USING THE SERVICES YOU EXPLICITLY ACKNOWLEDGE AND ACCEPT THESE HEIGHTENED RISKS. AVANA SHALL NOT BE LIABLE FOR THE FAILURE OF ANY MESSAGE TO SEND TO OR BE RECEIVED BY THE INTENDED RECIPIENT IN THE INTENDED FORM, OR FOR DIMINUTION OF VALUE OF ANY CRYPTO ASSET ON ANY BLOCKCHAIN NETWORKS, AND AVANA MAKES NO REPRESENTATIONS OR WARRANTIES WITH RESPECT TO THE SAME.</p>

            <h4 id="disclaimer-of-warranties">9. Disclaimer of Warranties; Limitation of Liability; Indemnification</h4>
            <p>9.1. EXCEPT AS EXPRESSLY SET FORTH HEREIN, THE SERVICES ARE ISSUED ON AN &quot;AS-IS&quot; AND &quot;AS AVAILABLE&quot; BASIS AND AVANA DOES NOT MAKE ANY WARRANTIES WITH RESPECT TO SUCH &quot;AS-IS&quot; AND &quot;AS AVAILABLE&quot; BASIS OR OTHERWISE IN CONNECTION WITH THE TERMS (EXCEPT AS EXPRESSLY PROVIDED HEREIN) AND AVANA HEREBY DISCLAIMS ANY AND ALL EXPRESS, IMPLIED OR STATUTORY WARRANTIES AND CONDITIONS, INCLUDING ANY WARRANTIES OR CONDITIONS OF NON-INFRINGEMENT, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AVAILABILITY, ERROR-FREE OR UNINTERRUPTED OPERATION, AND ANY WARRANTIES ARISING FROM A COURSE OF DEALING, COURSE OF PERFORMANCE OR USAGE OF TRADE. TO THE EXTENT THAT AVANA MAY NOT, AS A MATTER OF APPLICABLE LAW, DISCLAIM ANY IMPLIED WARRANTY OR CONDITION, THE SCOPE AND DURATION OF SUCH WARRANTY OR CONDITION SHALL BE APPLIED TO THE MINIMUM EXTENT PERMITTED UNDER SUCH APPLICABLE LAW.</p>
            <p>9.2. IN NO EVENT SHALL AVANA BE LIABLE TO YOU FOR ANY CONSEQUENTIAL, INDIRECT, INCIDENTAL OR SPECIAL DAMAGES OF ANY TYPE OR NATURE HOWEVER ARISING, INCLUDING, WITHOUT LIMITATION, EXEMPLARY OR PUNITIVE DAMAGES, LOST DATA, LOST PROFITS OR REVENUES OR DIMINUTION IN VALUE, ARISING OUT OF OR RELATING TO THE SERVICES OR YOUR USE OF THE AVANA PROTOCOL, WHETHER OR NOT THE POSSIBILITY OF SUCH DAMAGES HAS BEEN DISCLOSED TO OR COULD HAVE BEEN REASONABLY FORESEEN BY YOU, REGARDLESS OF THE LEGAL OR EQUITABLE THEORY (WHETHER IN CONTRACT, TORT OR OTHERWISE) UPON WHICH THE CLAIM IS BASED. IN ADDITION, UNDER NO CIRCUMSTANCES SHALL AVANA&apos;S AGGREGATE LIABILITY UNDER THE TERMS EXCEED ONE-HUNDRED U.S. DOLLARS ($100.00).</p>
            <p>9.3. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES. ACCORDINGLY, SOME OF THE LIMITATIONS SET FORTH ABOVE MAY NOT APPLY TO YOU. IF YOU ARE DISSATISFIED WITH THE SERVICES, YOU UNDERSTAND AND AGREE THAT YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USING THE SERVICES.</p>
            <p>9.4. You agree, at your own expense, to indemnify, defend and hold harmless Avana and our partners and their respective owners, members, agents, directors, officers, employees, representatives, successors and assigns against any claim, suit, action or other proceeding from and against any and all claims, damages, liabilities, costs and expenses, including reasonable attorneys&apos; and experts&apos; fees, arising out of or in connection with (i) your use of the Services, Third-Party Services, including, for the avoidance of doubt, applications or links made available via the Services; (ii) any breach or violation of the Terms by you; (iii) any material, information or content submitted or provided by you; or (iv) any deletions, additions, insertions or alterations to, or any unauthorized use of, the Services by you. You agree to pay any and all costs, damages and expenses, including but not limited to reasonable attorneys&apos; fees and costs awarded against or otherwise incurred by or in connection with or arising from any such claim, suit, action or proceeding attributable to any such claim. We reserve the right, at our own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will fully cooperate with us in asserting any available defense.</p>

            <h4 id="dispute-resolution">10. Dispute Resolution; Agreement to Arbitrate</h4>
            <p>10.1. All disputes, claims and controversies, whether based on past, present or future events, arising out of or relating to statutory or common law claims, the breach, termination, enforcement, interpretation or validity of any provision of the Terms and the determination of the scope or applicability of your agreement to arbitrate any dispute, claim or controversy originating from the Terms, shall be finally and exclusively settled under the JAMS Optional Expedited Arbitration Procedures. The arbitration shall be held on a confidential basis before a single arbitrator who shall be selected pursuant to JAMS rules, including where applicable the JAMS&apos; Mass Arbitration Procedures and Guidelines. The arbitration will be held in New York, New York. Any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction. If for any reason a claim by law or equity must proceed in court rather than in arbitration you hereby agree to waive any right to a jury trial and any claim may be brought only in a Federal District Court or a New York state court located in New York County, New York.</p>
            <p>10.2. The arbitrator will apply the substantive law of the State of New York, excluding its conflict or choice of law rules.</p>
            <p>10.3. Nothing in the Terms will preclude the parties from seeking provisional remedies in aid of arbitration from a court of appropriate jurisdiction.</p>
            <p>10.4. A party must notify the other party of its intent to commence arbitration prior to commencing arbitration. You may provide such notice to Avana at the email address set forth in Section 12.2. The notice must specify the date on which the arbitration demand is intended to be filed, which must be at least thirty (30) days after the date of the notice. During this time period, the parties will meet for the purpose of resolving the dispute prior to commencing arbitration.</p>
            <p>10.5. Subject to Section 10.4, each party may commence arbitration by providing to JAMS and the other party to the dispute a written demand for arbitration, stating the subject of the dispute and the relief requested.</p>
            <p>10.6. The parties will keep confidential the existence of the arbitration, the arbitration proceeding, the hearing and the arbitrator&apos;s decision, except: (i) as necessary to prepare for and conduct the arbitration hearing on the merits; (ii) in connection with a court application for a preliminary remedy, or confirmation of an arbitrator&apos;s decision or its enforcement; (iii) Avana may disclose the arbitrator&apos;s decision in confidential settlement negotiations; (iv) each party may disclose as necessary to professional advisors that are subject to a strict duty of confidentiality; and (v) as applicable law otherwise requires. The parties, witnesses and arbitrator will treat as confidential and will not disclose to any third person (other than witnesses or experts) any documentary or other evidence produced in any arbitration, except as applicable law so requires or if the evidence was obtained from the public domain or was otherwise obtained independently from the arbitration.</p>
            <p>10.7. In the case of a conflict between the provisions of this Section 10 and the rules of JAMS, the provisions of this Section 10 shall prevail.</p>
            <p>10.8. To the extent permitted by applicable law, any dispute arising out of or relating to the Terms, whether in arbitration or in court, shall be conducted only on an individual basis and not in a class, consolidated or representative action. Notwithstanding any other provision of the Terms or the rules of JAMS, disputes regarding the interpretation, applicability or enforceability of this class waiver may be resolved only by a court and not by an arbitrator. If this waiver of class or consolidated actions is deemed invalid or unenforceable, neither party is entitled to arbitration.</p>
            <p>10.9. If for any reason a claim or dispute proceeds in court rather than through arbitration, each party knowingly and irrevocably waives any right to trial by jury in any action, proceeding or counterclaim arising out of or relating to the Terms.</p>

            <h4 id="third-party-services">11. Third-Party Services</h4>
            <p>11.1. By using the Services, you may view, use and have access to the content, products, services, protocols, software (including open source software), smart contracts, Wallets (as defined below) and applications of one or more third parties (&quot;<strong>Third-Party Services</strong>&quot;), via linked or plugged-in technologies to the Services. Your reliance on, access or use of any Third-Party Services in connection with using the Services will also be governed by the terms and conditions and policies of the applicable third-party service provider (<em>e.g.</em>, a digital wallet provider). You understand and agree that any such third-party terms and conditions and policies may involve fees or other charges and include disclaimers or particular risk warnings about the reliance on or the accuracy of any information or with using such Third-Party Services. It is your responsibility to understand the terms and conditions and policies of any such third-party service provider, including how those service providers use any of your data or other information under their privacy policies. Any such terms and conditions and policies may provide for less security than Avana. You understand and agree that any Third-Party Services are provided for your convenience only, and we do not make any warranty, express or implied, with respect to any Third-Party Services. We do not verify or control any Third-Party Services, and as a result, we do not guarantee, endorse, express or implied, or recommend any Third-Party Services to any or all users of the Services. We are therefore not responsible for the availability, content, validity, timeliness, completeness, reliability, integrity, quality, legality, usefulness, safety or accuracy of any Third-Party Services, or any intellectual property rights therein, that may be linked to or from the Services. Your reliance on, access and use of any Third-Party Services is at your own risk, and we disclaim all responsibility and liability for any losses that result out of same. We have no responsibility for Third-Party Services that may be misleading, incomplete, erroneous, offensive, indecent or otherwise objectionable to you or under the law in your jurisdiction, or which contain malware, vulnerabilities or any other types of malicious software, smart contracts, domains or computer code. The choice to rely on, access and use Third-Party Services is in your own discretion, and you are solely responsible for ensuring that your reliance, access or use is in compliance with all applicable laws. This paragraph shall be interpreted broadly and covers, each to the extent applicable, websites, other crypto-native technologies and all other applications (decentralized or otherwise) made available via the Services or any links made available through the Services.</p>
            <p>11.2. To access the Services or the Avana Protocol you must connect a compatible digital wallet software (&quot;<strong>Wallet</strong>&quot;). You are responsible for maintaining the confidentiality of any private key controlled by your Wallet and are fully responsible for any and all messages or conduct signed with your private key. We accept no responsibility or liability to you in connection with your use of a Wallet or the crypto assets used in connection therewith, and make no representations and warranties regarding how the Services, the Avana Protocol, or any other Third-Party Services will operate or be compatible with any specific Wallet. We reserve the right, in our sole discretion, to prohibit certain Wallet addresses from being able to use or engage in transactions via the Services or from using other aspects of the Services.</p>
            <p>11.3. WE DISCLAIM ANY AND ALL LIABILITY, INCLUDING ANY EXPRESS OR IMPLIED WARRANTIES, WHETHER ORAL OR WRITTEN, FOR WEBSITES, SERVICES, GOODS, INFORMATION, ADVERTISEMENTS OR OTHER THIRD-PARTY SERVICES THAT MAY BE LINKED TO OR FROM, OR MADE AVAILABLE VIA, THE SERVICES. YOU ACKNOWLEDGE THAT NO REPRESENTATION HAS BEEN MADE BY US AS TO THE FITNESS OF THE SERVICES, GOODS, ADVERTISEMENTS OR OTHER THIRD-PARTY SERVICES THAT MAY BE LINKED TO, FROM OR MADE AVAILABLE VIA THE SERVICES. YOUR USE OF THIRD-PARTY SERVICES IS AT YOUR SOLE RISK AND IS SUBJECT TO ANY ADDITIONAL TERMS, CONDITIONS AND POLICIES APPLICABLE TO SUCH THIRD-PARTY SERVICES (SUCH AS TERMS OF USE AND THE PRIVACY POLICY OF THE PROVIDERS OF SUCH THIRD-PARTY SERVICES).</p>
            <p>11.4. You may not link to the Services or integrate or make use of all or part of the Services in ways that would confuse or mislead visitors as to the nature and origin of the Services&apos; content.</p>

            <h4 id="general-provisions">12. General Provisions</h4>
            <p>12.1. <em>Electronic Communications</em>. By accessing or using the Services, you consent to receive electronic communications.</p>
            <p>12.2. <em>Notices</em>. Avana may provide you with notice and other communications via electronic communications as permitted by Section 12.1. You may provide us with notice by sending an email address to{" "}<a href="mailto:legal@avana.cc">legal@avana.cc</a>. All notices will be deemed effective upon dispatch.</p>
            <p>12.3. <em>Waivers</em>. For a waiver to be deemed effective, a waiver must be in writing signed by the waiving party. The failure of either party to enforce any provision of the Terms will not constitute a waiver of that party&apos;s rights to subsequently enforce the provision.</p>
            <p>12.4. <em>Cumulative Rights; Injunctions</em>. The rights and remedies of the parties under the Terms are cumulative, and each party may exercise any of its rights and enforce any of its remedies under the Terms, along with all other rights and remedies available to it at law, in equity or otherwise. Any material breach by a party of the Terms could cause the non-breaching party irreparable harm for which the non-breaching party has no adequate remedies at law. Accordingly, the non-breaching party is entitled to seek specific performance or injunctive relief for any such breach.</p>
            <p>12.5. <em>Severability</em>. If any provision of the Terms is declared to be invalid, illegal or unenforceable by a court of competent jurisdiction, then the validity, legality and enforceability of the remaining provisions contained herein shall not be affected thereby and the remainder of the provisions of the Terms shall remain valid, legal and enforceable to the fullest extent permitted by law.</p>
            <p>12.6. <em>Successors and Assigns</em>. You may not transfer or assign the Terms or any rights or obligations hereunder, by operation of law or otherwise and any such attempted assignment shall be void. Avana reserves the right to freely transfer or assign the Terms and the rights and obligations hereunder to any third party at any time without your consent and prior notice to you. If you object to any such transfer or assignment, you may stop using the Services.</p>
            <p>12.7. <em>Relationship of the Parties</em>. Nothing contained in the Terms shall constitute you and Avana as members of any partnership, joint venture, association, syndicate, unincorporated business or similar assignment as a result of or by virtue of the relationship established by the Terms.</p>
            <p>12.8. <em>Governing Law</em>. The Terms shall be solely and exclusively governed, construed and enforced in accordance with the laws of the State of New York without giving effect to conflict of law rules or principles that would cause the application of the laws of any other jurisdiction.</p>
            <p>12.9. <em>Entire Agreement</em>. The Terms constitute the entire agreement and understanding between you and Avana, and supersedes all previous communications, representations or agreements, whether written or oral, with respect to the subject matter hereof.</p>
            <p>12.10. <em>No Third-Party Beneficiaries</em>. The Terms are not intended and shall not be construed to create any rights or remedies in any parties other than you and Avana, and no other person shall assert any rights as a third-party beneficiary hereunder.</p>
          </div>

          {/* Sidebar navigation */}
          <div className="hidden w-[17rem] shrink-0 xl:block xl:sticky xl:top-28 xl:pt-4">
            <ScrollSpySidebar sections={sections} sectionColor="rose" />
          </div>
        </div>
      </article>
    </section>
    </LocalizedLegal>
  )
}
